version: '3.8'
services:
  dev-postgres:
    image: postgres:15.0
    container_name: dev-postgres
    restart: always
    ports:
      - 5432:5432 #Port Pc and port container
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
