version: '3.8'
services:
#  redis: # Name of container
#    image: redis
#    ports:
#      - 6379:6379
#    volumes:
#      - redis:/data
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    restart: always
#    ports:
#      - 5432:5432 #Port Pc and port container
##    expose:
##      - 5434
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: postgres
##    - POSTGRES_PGAUDIT_LOG=READ,WRITE
##    - POSTGRES_LOG_HOSTNAME=true
##    - POSTGRES_REPLICATION_MODE=master
##    - POSTGRES_REPLICATION_USER=repl_user
##    - POSTGRES_REPLICATION_PASSWORD=repl_password
##    - POSTGRES_USERNAME=postgres
##    - POSTGRES_DATABASE=postgres
##    - ALLOW_EMPTY_PASSWORD=yes
##    - POSTGRES_HOST_AUTH_METHOD=trust
##      POSTGRES_LOG_HOSTNAME: true
##      POSTGRES_REPLICATION_MODE: master
##      POSTGRES_REPLICATION_USER: repl_user
##      POSTGRES_REPLICATION_PASSWORD: repl_password
##      POSTGRES_USER: postgres
##      POSTGRES_PASSWORD: 123456
##      POSTGRES_DB: postgres
#    volumes:
#      - master-data:/var/lib/postgresql/data
#    networks:
#      - postgres-net
#    command: postgres -c max_connections=300
#  postgres-secondary:
#    image: postgres:latest
#    restart: always
#    depends_on:
#      - postgres
##    restart: always
#    container_name: postgres-secondary
##    ports:
##      - 5433:5432 #Port Pc and port container
###    expose:
##      - 5435
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_MASTER_HOST: postgres
##      - POSTGRES_USERNAME=postgres
##      - POSTGRES_PASSWORD=123456
##      - POSTGRES_MASTER_HOST=postgres
##      - POSTGRES_PGAUDIT_LOG=READ,WRITE
##      - POSTGRES_LOG_HOSTNAME=true
##      - POSTGRES_REPLICATION_MODE=slave
##      - POSTGRES_REPLICATION_USER=repl_user
##      - POSTGRES_REPLICATION_PASSWORD=repl_password
##      - POSTGRES_MASTER_PORT_NUMBER=5432
##      - POSTGRES_HOST_AUTH_METHOD=trust
##      POSTGRES_USERNAME: postgres
##      POSTGRES_PASSWORD: 123456
##      POSTGRES_DB: postgres
##      POSTGRES_MASTER_HOST: postgresql-master
##      POSTGRES_LOG_HOSTNAME: true
##      POSTGRES_REPLICATION_MODE: slave
##      POSTGRES_REPLICATION_USER: repl_user
##      POSTGRES_REPLICATION_PASSWORD: repl_password
##      POSTGRES_MASTER_PORT_NUMBER: 5432
##    volumes:
##      - slave:/var/lib/postgresql/data
##    networks:
##      - final-year
#    volumes:
#        - replica-data:/var/lib/postgresql/data
#    networks:
#     - postgres-net
#    command: postgres -c max_connections=300 -c primary_conninfo='host=postgres port=5432 user=postgres password=123456' -c restore_command='pg_standby -c /etc/postgresql/standby.signal -d -s 2 -t /tmp/%f %p %r 2>> /var/lib/postgresql/data/standby.log' -c recovery_target_timeline='latest'
#  master:
#    image: postgres:latest
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: webapp_dev
#    volumes:
#      - master-data:/var/lib/postgresql/data
#    networks:
#      - db-network
#
#  slave:
#    image: postgres:latest
#    restart: always
##    ports:
##       - 5433:5432
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: slave
#      POSTGRES_MASTER_SERVICE_HOST: master
#      POSTGRES_MASTER_SERVICE_PORT: 5432
#    volumes:
#      - slave-data:/var/lib/postgresql/data
#    networks:
#       - db-network
#  master:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: webapp_dev
##      PGDATA: '/var/lib/postgresql/data/pgdata'
#    volumes:
#      - master-data:/var/lib/postgresql/data
#    expose:
#      - 5432
#    networks:
#      db-network:
#  slave:
#    image: postgres:latest
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: 123456
#      POSTGRES_DB: slave
##      PGDATA: '/var/lib/postgresql/data/pgdata'
#      REPLICATE_FROM: master
#    volumes:
#      - slave-data:/var/lib/postgresql/data
#    expose:
#      - 5432'
#    links:
#     - master
#    networks:
#      db-network:

  postgresql-master:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgresql-master:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      POSTGRES_REPLICATION_USER: replication_user
      POSTGRES_REPLICATION_PASSWORD: replication_password
    networks:
      - mynetwork
  postgresql-slave:
    image: postgres:latest
    ports:
      - '5433:5432'
    depends_on:
      - postgresql-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
#      POSTGRES_MASTER_SERVICE: postgresql-master
      POSTGRES_REPLICATION_MODE: true
      POSTGRES_REPLICATE_FROM: postgresql-master
      POSTGRES_MASTER_HOST: postgresql-master
      POSTGRES_REPLICATION_USER: replication_user
      POSTGRES_REPLICATION_PASSWORD: replication_password
    volumes:
      - postgresql-slave:/var/lib/postgresql/data
    networks:
      - mynetwork
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgresql-slave
      - postgresql-master
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - mynetwork
  backend:
     stdin_open: true
     build:
       context: ../final-year-danang-traval-backend
       dockerfile: Dockerfile
     restart: always
     container_name: back-end-API
     depends_on:
       - postgresql-master
       - postgresql-slave
#       - redis
     environment:
       DATABASE_URL : 'postgresql://postgres:123456@postgresql-slave:5432/postgres?schema=public'
       URL_NEXT: http://localhost
     ports:
       - 8080:8080
     expose:
       - 8080
     networks:
       - mynetwork
     volumes:
       - ../final-year-danang-traval-backend:/usr/src/app
#       - .:/usr/src/app
#       - ../final-year-danang-traval-backend/src/app/node_modules
#     volumes:
#       - ../final-year-danang-traval-backend:/usr/src/app
  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../frontend-nextjs/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
networks:
  mynetwork:
    driver: bridge
#    external: true
#    name: final-year
volumes:
  postgresql-master:
    driver: local
  postgresql-slave:
    driver: local
#      - slave-data:/var/lib/postgresql/data

# docker compose -p finalyear up -d
